name: Generate pdf from resume.html and commit it.

on:
  push:
    branches: [ main ]
    paths:
      - 'resume.html'

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Generate PDF with Puppeteer
        run: node scipts/generate-pdf.js

      - name: Commit and push
        run: |
          git config user.name ambaena
          git config user.email alfonsombaena@gmail.com
          git add resume.pdf
          git diff --quiet && git diff --staged --quiet || git commit -m "[BOT] 🤖: update resume.pdf with latest info"
          git push origin main
